// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiABkkqafsC6clxl9KmHmiZr2hT0mxI-g',
    appId: '1:643818771916:web:6c974b1b7884a19cd3f969',
    messagingSenderId: '643818771916',
    projectId: 'ecotrack-8ec69',
    authDomain: 'ecotrack-8ec69.firebaseapp.com',
    storageBucket: 'ecotrack-8ec69.firebasestorage.app',
    measurementId: 'G-QPJC5X3V1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu9WSPw7QGOzZjLuAbl50Nwg7x1eDh6Xo',
    appId: '1:643818771916:android:27b25c090af6f634d3f969',
    messagingSenderId: '643818771916',
    projectId: 'ecotrack-8ec69',
    storageBucket: 'ecotrack-8ec69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_gXkfCmIBrQ1xeNML80oK-XV2ysxErM',
    appId: '1:643818771916:ios:78f9224944d029b9d3f969',
    messagingSenderId: '643818771916',
    projectId: 'ecotrack-8ec69',
    storageBucket: 'ecotrack-8ec69.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_gXkfCmIBrQ1xeNML80oK-XV2ysxErM',
    appId: '1:643818771916:ios:78f9224944d029b9d3f969',
    messagingSenderId: '643818771916',
    projectId: 'ecotrack-8ec69',
    storageBucket: 'ecotrack-8ec69.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiABkkqafsC6clxl9KmHmiZr2hT0mxI-g',
    appId: '1:643818771916:web:9a10ff5311940ef1d3f969',
    messagingSenderId: '643818771916',
    projectId: 'ecotrack-8ec69',
    authDomain: 'ecotrack-8ec69.firebaseapp.com',
    storageBucket: 'ecotrack-8ec69.firebasestorage.app',
    measurementId: 'G-ZPV9J3HLZE',
  );
}
